services:
  backend:
    build:
      context: ./back-end
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
